{
 "title": "API Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Average request durations",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(\"http.route\", \"http.request.method\") (rate({\"http.server.request.duration_seconds_sum\", \"http.route\"!=\"\"}[$__range])) / sum by(\"http.route\", \"http.request.method\") (rate({\"http.server.request.duration_seconds_count\", \"http.route\"!=\"\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status codes count",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by(\"http.route\", \"http.request.method\", \"http.response.status_code\") (round(increase({\"http.server.request.duration_seconds_count\", \"http.route\"!=\"\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests count [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(\"http.route\") (round(increase({\"http.server.request.duration_seconds_count\", \"http.route\"!=\"\"}[10m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}