{
 "title": "Series Updater Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Average series update duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({\"scanlationtracker.series_update.duration_seconds_sum\"}[$__range])) / sum(rate({\"scanlationtracker.series_update.duration_seconds_count\"}[$__range]))",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Series update duration distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (round(increase({\"scanlationtracker.series_update.duration_seconds_bucket\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Series update duration [10m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase({\"scanlationtracker.series_update.duration_seconds_sum\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Added series count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(\"scanlation_group.name\") (round(increase({\"scanlationtracker.series_update.series_added_total\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Added chapters count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(\"scanlation_group.name\") (round(increase({\"scanlationtracker.series_update.chapters_added_total\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Added chapters",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "sum by(\"scanlation_group.name\") ({\"scanlationtracker.series_update.chapters_added_total\"})",
     "legendFormat": "{{scanlation_group.name}}"
    }
   ]
  }
 ]
}