{
 "title": "Series Updater Logs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "severity", "label": "Severity" },
   { "name": "scanlation_group", "label": "Scanlation Group" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Logs by Severity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(severity_text) (count_over_time({service_name=\"ScanlationTracker.SeriesUpdater\"} | GroupName=~\"${scanlation_group:default:.*}\" $filter [$__range]))",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Logs by Scanlation Group",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(GroupName) (count_over_time({service_name=\"ScanlationTracker.SeriesUpdater\"} | GroupName!=\"\" | severity_text=~\"${severity:default:.*}\" $filter [$__range]))",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count (count_over_time({service_name=\"ScanlationTracker.SeriesUpdater\"} | severity_text=~\"${severity:default:.*}\" | GroupName=~\"${scanlation_group:default:.*}\" $filter [$__interval]))",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ScanlationTracker.SeriesUpdater\"} | severity_text=~\"${severity:default:.*}\" | GroupName=~\"${scanlation_group:default:.*}\" $filter"
    }
   ]
  }
 ]
}