name: .NET CI

on:
  push:
    branches:
      - master
    paths:
      - backend/**

jobs:
  build-and-test:
    name: Build and test .NET projects
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: dotnet build /warnaserror

    - name: Test
      run: dotnet test --no-build

  build-and-push-seriesupdater-image:
    name: Build and push seriesupdater image to GitHub Container Registry
    uses: ./.github/workflows/push-image.yml
    with:
      dockerfile: backend/ScanlationTracker.SeriesUpdater/Dockerfile
      image-name: scanlationtracker.seriesupdater
    secrets: inherit

  build-and-push-api-image:
    name: Build and push api image to GitHub Container Registry
    uses: ./.github/workflows/push-image.yml
    with:
      dockerfile: backend/ScanlationTracker.Api/Dockerfile
      image-name: scanlationtracker.api
    secrets: inherit

  build-and-push-migrationseeding-image:
    name: Build and push migration.seeding image to GitHub Container Registry
    uses: ./.github/workflows/push-image.yml
    with:
      dockerfile: backend/ScanlationTracker.Migration.Seeding/Dockerfile
      image-name: scanlationtracker.migration.seeding
    secrets: inherit
