name: .NET CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build .NET projects
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: dotnet build /warnaserror
