name: Buid and push Docker image to GitHub Container Registry

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      image-name:
        required: true
        type: string

jobs:
  build-and-push-image:
    name: Build and push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.REPOSITORY_OWNER }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Convert GITHUB_REPOSITORY_OWNER to lowercase
      id: to-lower
      run: echo "repository_owner_lowercase=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image to GitHub Container Registry
      uses: docker/build-push-action@v6
      with:
        file: ${{ inputs.dockerfile }}
        tags: ghcr.io/${{ steps.to-lower.outputs.repository_owner_lowercase }}/${{ inputs.image-name }}:latest
        cache-from: type=gha,scope=${{ inputs.image-name }}
        cache-to: type=gha,mode=max,scope=${{ inputs.image-name }}
        push: true
